// Data misi dipisahkan dari tampilan dan mesin simulasi.
// Enam misi awal dipertahankan agar kemajuan lama tetap cocok.

const ORIGINAL_MISSIONS = [
  {
    id: 1,
    title: 'Jejak lurus',
    concept: 'Urutan dasar',
    difficulty: 'Mulai dari sini',
    story: 'Buku ada di ujung lorong. Susun langkah robot dari kiri ke kanan.',
    start: { x: 0, y: 2, dir: 0 },
    book: { x: 2, y: 2 },
    target: { x: 3, y: 2 },
    solution: ['forward', 'forward', 'pickup', 'forward', 'deliver'],
    initial: ['forward', 'right', 'pickup', 'forward', 'deliver'],
    hints: [
      'Amati petak buku dan kartu tepat sebelum “ambil buku”.',
      'Robot perlu benar-benar berada di petak buku saat mengambil.',
      'Hitung langkah lurus dari garis start sampai buku. Periksa apakah jumlahnya sudah cukup.',
    ],
  },
  {
    id: 2,
    title: 'Belok ke rak',
    concept: 'Urutan + arah',
    difficulty: 'Naik satu tingkat',
    story: 'Rak perpustakaan ada di atas lorong. Satu belokan akan membawa robot ke sana.',
    start: { x: 0, y: 3, dir: 0 },
    book: { x: 1, y: 3 },
    target: { x: 1, y: 1 },
    solution: ['forward', 'pickup', 'left', 'forward', 'forward', 'deliver'],
    initial: ['forward', 'pickup', 'right', 'forward', 'forward', 'deliver'],
    hints: [
      'Lihat arah hadap robot sebelum kartu belok dijalankan.',
      'Robot harus naik menuju rak, bukan turun ke bawah.',
      'Coba bandingkan belok kiri dan kanan dengan posisi rak pada peta.',
    ],
  },
  {
    id: 3,
    title: 'Ulangi langkah',
    concept: 'Pengulangan',
    difficulty: 'Pakai pola',
    story: 'Lorongnya lebih panjang. Satu kartu ulang dapat menggantikan beberapa kartu maju.',
    start: { x: 0, y: 2, dir: 0 },
    book: { x: 3, y: 2 },
    target: { x: 4, y: 2 },
    solution: ['loop3', 'pickup', 'forward', 'deliver'],
    initial: ['loop2', 'pickup', 'forward', 'deliver'],
    hints: [
      'Perhatikan jarak robot ke buku dan baca angka pada kartu ulang.',
      'Kartu ulang menjalankan “maju” beberapa kali, bukan satu kali.',
      'Jumlah pengulangan harus menutup seluruh jarak dari start ke buku.',
    ],
  },
  {
    id: 4,
    title: 'Naik lalu melaju',
    concept: 'Pengulangan + arah',
    difficulty: 'Gabungkan pola',
    story: 'Naik dua petak, ambil buku, lalu melaju ke rak di sebelah kanan.',
    start: { x: 0, y: 3, dir: 0 },
    book: { x: 0, y: 1 },
    target: { x: 3, y: 1 },
    solution: ['left', 'loop2', 'pickup', 'right', 'loop3', 'deliver'],
    initial: ['left', 'loop2', 'pickup', 'left', 'loop3', 'deliver'],
    hints: [
      'Setelah mengambil buku, bandingkan arah hadap robot dengan posisi perpustakaan.',
      'Robot sudah berada di baris yang benar. Sekarang perpustakaan ada di kanan.',
      'Perintah setelah “ambil buku” perlu membuat robot menghadap ke arah tujuan.',
    ],
  },
  {
    id: 5,
    title: 'Naik ke lantai atas',
    concept: 'Urutan + pengulangan',
    difficulty: 'Cek waktunya',
    story: 'Robot harus sampai ke buku dulu sebelum berbelok ke lantai atas.',
    start: { x: 0, y: 2, dir: 0 },
    book: { x: 2, y: 2 },
    target: { x: 2, y: 0 },
    solution: ['forward', 'forward', 'pickup', 'left', 'loop2', 'deliver'],
    initial: ['forward', 'left', 'pickup', 'loop2', 'deliver'],
    hints: [
      'Perhatikan kartu yang dijalankan sebelum robot tiba di petak buku.',
      'Robot harus berjalan dua langkah mendatar sebelum mengambil.',
      'Ada urutan sederhana: sampai di buku, ambil, baru mengubah arah.',
    ],
  },
  {
    id: 6,
    title: 'Rute campuran',
    concept: 'Tantangan akhir',
    difficulty: 'Detektif andal',
    story: 'Gabungkan dua pengulangan dan dua belokan untuk menemukan rute paling rapi.',
    start: { x: 0, y: 3, dir: 0 },
    book: { x: 2, y: 3 },
    target: { x: 4, y: 1 },
    solution: ['loop2', 'pickup', 'left', 'loop2', 'right', 'loop2', 'deliver'],
    initial: ['loop2', 'pickup', 'left', 'loop3', 'right', 'loop2', 'deliver'],
    hints: [
      'Jalankan dan amati apakah robot berhenti di baris perpustakaan atau melewatinya.',
      'Periksa angka pada pengulangan pertama setelah robot berbelok ke atas.',
      'Hitung jarak ke atas dari buku sampai baris perpustakaan sebelum belok kanan lagi.',
    ],
  },
];

const ORIGINAL_LEARNING = {
  1: {
    objective: 'Susun langkah agar robot tiba di buku sebelum mengambilnya.',
    takeaway: 'Urutan kartu menentukan kapan robot berjalan, mengambil, dan mengantar.',
    reflection: {
      question: 'Mengapa kartu “ambil buku” perlu dijalankan setelah robot sampai di buku?',
      choices: ['Supaya warna robot berubah.', 'Robot hanya bisa mengambil buku di petak buku.', 'Robot bisa mengambil buku dari petak mana saja.'],
      correctIndex: 1,
      explanations: [
        'Warna robot tidak menentukan apakah buku dapat diambil. Perhatikan posisi robot.',
        'Benar! Robot perlu berada di petak buku dulu. Urutan langkah membantu robot sampai di sana.',
        'Buku tidak bisa diambil dari jauh. Robot harus datang ke petak buku lebih dahulu.',
      ],
    },
  },
  2: {
    objective: 'Periksa arah belok agar buku dibawa menuju perpustakaan.',
    takeaway: 'Belok mengubah arah hadap; maju mengubah posisi robot.',
    reflection: {
      question: 'Apa yang berubah saat robot menjalankan kartu belok?',
      choices: ['Arah hadap robot.', 'Robot langsung pindah dua petak.', 'Buku langsung sampai di perpustakaan.'],
      correctIndex: 0,
      explanations: [
        'Benar! Robot berputar di petaknya. Kartu maju berikutnya mengikuti arah yang baru.',
        'Belok tidak memindahkan robot. Robot baru pindah saat menjalankan kartu maju.',
        'Belok hanya mengubah arah. Robot masih perlu membawa dan mengantar bukunya.',
      ],
    },
  },
  3: {
    objective: 'Cocokkan jumlah pengulangan dengan jarak menuju buku.',
    takeaway: 'Ulang tiga kali menjalankan satu langkah maju sebanyak tiga kali.',
    reflection: {
      question: 'Kartu “ulang 3×: maju” sama dengan susunan mana?',
      choices: ['Maju, lalu belok, lalu maju.', 'Satu kartu maju saja.', 'Maju, maju, maju.'],
      correctIndex: 2,
      explanations: [
        'Kartu ulang ini hanya mengulang maju. Kartu belok perlu ditambahkan sendiri.',
        'Angka tiga berarti maju dilakukan tiga kali, bukan satu kali.',
        'Benar! Satu kartu ulang dapat menggantikan tiga kartu maju yang berurutan.',
      ],
    },
  },
  4: {
    objective: 'Gabungkan belokan dan pengulangan untuk dua bagian perjalanan.',
    takeaway: 'Pengulangan maju selalu mengikuti arah hadap robot saat itu.',
    reflection: {
      question: 'Robot menghadap ke atas. Ke mana robot bergerak saat menjalankan “ulang 2×: maju”?',
      choices: ['Selalu ke kanan.', 'Dua langkah ke atas.', 'Robot berputar dua kali.'],
      correctIndex: 1,
      explanations: [
        'Maju mengikuti arah robot. Jika menghadap ke atas, robot tidak bergerak ke kanan.',
        'Benar! Robot maju dua kali ke arah yang sedang dihadapinya.',
        'Yang diulang adalah maju, bukan belok. Arah hadapnya tetap selama pengulangan.',
      ],
    },
  },
  5: {
    objective: 'Perbaiki urutan sampai di buku, mengambil, lalu melanjutkan perjalanan.',
    takeaway: 'Perintah yang benar tetap bisa gagal jika dijalankan pada waktu yang salah.',
    reflection: {
      question: 'Semua jenis kartu sudah benar, tetapi “ambil buku” dijalankan terlalu cepat. Apa yang perlu diperiksa?',
      choices: ['Urutan kartu dan posisi robot saat mengambil.', 'Warna petak di peta.', 'Volume suara robot.'],
      correctIndex: 0,
      explanations: [
        'Benar! Jenis perintah saja belum cukup. Robot juga harus berada di tempat yang tepat saat perintah dijalankan.',
        'Warna petak membantu melihat peta, tetapi tidak mengubah urutan program.',
        'Suara boleh membantu mengamati. Keberhasilan tetap ditentukan perintah dan posisi robot.',
      ],
    },
  },
  6: {
    objective: 'Hitung jarak setiap bagian rute sebelum robot berbelok lagi.',
    takeaway: 'Rute yang berbelok perlu dihitung per bagian, bukan hanya total langkahnya.',
    reflection: {
      question: 'Mengapa jarak sebelum belok perlu dihitung terpisah dari jarak setelah belok?',
      choices: ['Karena kartu ulang hanya boleh dipakai sekali.', 'Karena semua belokan memindahkan robot.', 'Karena setiap bagian rute bisa punya arah dan panjang berbeda.'],
      correctIndex: 2,
      explanations: [
        'Kartu ulang boleh digunakan beberapa kali. Setiap kali, periksa jarak bagian rutenya.',
        'Belok mengubah arah, bukan posisi. Jarak maju tetap perlu dihitung.',
        'Benar! Hitung sampai titik belok, ubah arah, lalu hitung bagian perjalanan berikutnya.',
      ],
    },
  },
};

const NEW_MISSIONS = [
  {
    id: 7,
    stageId: 2,
    title: 'Lorong di balik rak',
    concept: 'Urutan + rute aman',
    difficulty: 'Kenali penghalang',
    story: 'Rak menutup lorong lurus setelah buku. Cari jalan di atas rak untuk mengantarnya.',
    objective: 'Letakkan belokan pada waktu yang tepat agar robot tidak menabrak rak.',
    takeaway: 'Urutan belok dan maju menentukan apakah robot melewati jalan yang aman.',
    size: { width: 6, height: 4 },
    start: { x: 0, y: 3, dir: 0 },
    book: { x: 2, y: 3 },
    target: { x: 5, y: 1 },
    walls: [{ x: 3, y: 3 }, { x: 3, y: 2 }],
    solution: ['loop2', 'pickup', 'left', 'loop2', 'right', 'loop3', 'deliver'],
    initial: ['loop2', 'pickup', 'loop3', 'left', 'loop2', 'right', 'deliver'],
    hints: [
      'Amati petak tepat di depan robot setelah buku diambil. Apakah jalan lurus masih terbuka?',
      'Ada rak yang tidak bisa dilewati. Periksa kartu sebelum robot mencoba maju ke rak.',
      'Robot perlu mengubah arah sebelum melanjutkan perjalanan melewati sisi rak. Periksa urutan belok dan maju.',
    ],
    reflection: {
      question: 'Jika robot menabrak rak saat maju, apa yang berguna untuk diperiksa?',
      choices: ['Arah robot dan kartu sebelum tabrakan.', 'Apakah suara efek sudah nyala.', 'Apakah semua kartu bisa dihapus.'],
      correctIndex: 0,
      explanations: [
        'Benar! Arah dan urutan kartu membantu menemukan mengapa robot masuk ke petak rak.',
        'Suara tidak membuka jalan yang tertutup. Periksa posisi, arah, dan kartu robot.',
        'Menghapus semua kartu belum menjelaskan kesalahannya. Coba amati titik tabrakan dulu.',
      ],
    },
  },
  {
    id: 8,
    stageId: 2,
    title: 'Berangkat dari kanan',
    concept: 'Arah + pengulangan',
    difficulty: 'Ganti sudut pandang',
    story: 'Kali ini robot berangkat dari sisi kanan. Arah belok tetap mengikuti arah hadap robot.',
    objective: 'Gunakan arah hadap robot untuk memilih belokan, bukan arah layar saja.',
    takeaway: 'Kiri dan kanan pada kartu dihitung dari arah hadap robot.',
    size: { width: 6, height: 4 },
    start: { x: 5, y: 3, dir: 2 },
    book: { x: 3, y: 3 },
    target: { x: 0, y: 1 },
    walls: [{ x: 2, y: 3 }, { x: 2, y: 2 }],
    solution: ['loop2', 'pickup', 'right', 'loop2', 'left', 'loop3', 'deliver'],
    initial: ['loop2', 'pickup', 'left', 'loop2', 'left', 'loop3', 'deliver'],
    hints: [
      'Lihat panah arah robot saat buku diambil. Kali ini robot menghadap ke mana?',
      'Perpustakaan ada di baris atas, tetapi belok dilihat dari arah hadap robot.',
      'Bayangkan kamu menghadap seperti robot. Bandingkan arah sesudah belok kiri dan belok kanan.',
    ],
    reflection: {
      question: 'Saat robot menghadap ke kiri peta, belok kanan membuat robot menghadap ke mana?',
      choices: ['Ke bawah peta.', 'Ke atas peta.', 'Tetap ke kiri peta.'],
      correctIndex: 1,
      explanations: [
        'Saat menghadap kiri, belok kiri yang mengarah ke bawah. Bayangkan ikut menghadap seperti robot.',
        'Benar! Kanan mengikuti arah robot. Dari menghadap kiri peta, belok kanan mengarah ke atas.',
        'Kartu belok mengubah arah hadap. Robot tidak tetap menghadap kiri.',
      ],
    },
  },
  {
    id: 9,
    stageId: 3,
    title: 'Jalan memutar',
    concept: 'Rute sebelum mengambil',
    difficulty: 'Baca seluruh peta',
    story: 'Rak menghalangi jalan dari start. Robot harus memutar dahulu sebelum menemukan buku.',
    objective: 'Rencanakan jalan menuju buku dan jalan menuju perpustakaan sebagai dua bagian.',
    takeaway: 'Perjalanan ke buku juga perlu direncanakan sebelum kartu ambil dijalankan.',
    size: { width: 6, height: 5 },
    start: { x: 0, y: 4, dir: 0 },
    book: { x: 3, y: 2 },
    target: { x: 5, y: 0 },
    walls: [{ x: 1, y: 4 }, { x: 1, y: 3 }, { x: 2, y: 3 }, { x: 3, y: 3 }],
    solution: ['left', 'loop2', 'right', 'loop3', 'pickup', 'left', 'loop2', 'right', 'loop2', 'deliver'],
    initial: ['loop2', 'left', 'right', 'loop3', 'pickup', 'left', 'loop2', 'right', 'loop2', 'deliver'],
    hints: [
      'Amati jalan di depan robot sebelum kartu pertama dijalankan.',
      'Robot belum membawa buku. Cari lorong terbuka untuk mencapai petak buku lebih dahulu.',
      'Periksa urutan dua kartu pertama. Robot perlu menghadap lorong terbuka sebelum mengulang langkah.',
    ],
    reflection: {
      question: 'Kapan perintah “ambil buku” boleh dijalankan, meskipun robot melewati jalan memutar?',
      choices: ['Segera setelah kartu belok.', 'Setelah semua kartu maju habis.', 'Saat robot sudah berada di petak buku.'],
      correctIndex: 2,
      explanations: [
        'Belok saja belum menjamin robot sampai di buku. Lihat posisi robot setelah perjalanan.',
        'Masih ada perjalanan setelah mengambil buku. Kartu ambil tidak harus menunggu semua kartu maju habis.',
        'Benar! Panjang atau bentuk rute boleh berbeda. Syarat mengambil tetap sama: robot berada di petak buku.',
      ],
    },
  },
  {
    id: 10,
    stageId: 3,
    title: 'Hitung sebelum belok',
    concept: 'Gabungan pengulangan',
    difficulty: 'Cek langkah tambahan',
    story: 'Buku ada sebelum rak penghalang. Setelah mengambil buku, robot naik melalui lorong panjang.',
    objective: 'Bedakan langkah yang diperlukan sebelum buku dan setelah buku.',
    takeaway: 'Pengulangan dan satu langkah tambahan bisa digabung, tetapi harus berada di bagian rute yang tepat.',
    size: { width: 6, height: 5 },
    start: { x: 5, y: 4, dir: 2 },
    book: { x: 2, y: 4 },
    target: { x: 2, y: 0 },
    walls: [{ x: 1, y: 4 }, { x: 3, y: 2 }, { x: 4, y: 2 }],
    solution: ['loop3', 'pickup', 'right', 'loop3', 'forward', 'deliver'],
    initial: ['loop3', 'forward', 'pickup', 'right', 'loop3', 'forward', 'deliver'],
    hints: [
      'Amati kapan robot sampai di buku dan apa yang dilakukan kartu berikutnya.',
      'Ada satu langkah yang membawa robot melewati buku menuju rak. Periksa bagian sebelum mengambil.',
      'Hitung jarak ke buku dan jarak naik secara terpisah. Langkah tambahan tidak selalu diperlukan di kedua bagian.',
    ],
    reflection: {
      question: 'Tanpa belok di antaranya, “ulang 3×: maju” lalu “maju 1 langkah” membuat robot maju berapa kali?',
      choices: ['Empat kali.', 'Tiga kali.', 'Satu kali.'],
      correctIndex: 0,
      explanations: [
        'Benar! Tiga langkah dari pengulangan ditambah satu langkah lagi menjadi empat.',
        'Tiga adalah jumlah pada kartu ulang saja. Kartu maju setelahnya menambah satu langkah.',
        'Kartu ulang juga menjalankan maju. Hitung tiga langkahnya, lalu satu langkah tambahan.',
      ],
    },
  },
  {
    id: 11,
    stageId: 3,
    title: 'Buku di tikungan',
    concept: 'Urutan di sekitar rak',
    difficulty: 'Periksa titik belok',
    story: 'Buku berada di sisi rak. Pilih titik belok yang aman untuk membawanya mengitari rak.',
    objective: 'Temukan titik belok yang tidak mengarah ke rak penghalang.',
    takeaway: 'Satu perubahan urutan bisa memindahkan titik belok dan mengubah seluruh rute.',
    size: { width: 6, height: 5 },
    start: { x: 0, y: 4, dir: 3 },
    book: { x: 0, y: 1 },
    target: { x: 4, y: 3 },
    walls: [{ x: 1, y: 1 }, { x: 1, y: 2 }, { x: 2, y: 2 }, { x: 3, y: 2 }],
    solution: ['loop3', 'pickup', 'forward', 'right', 'loop3', 'forward', 'right', 'loop3', 'deliver'],
    initial: ['loop3', 'pickup', 'right', 'forward', 'loop3', 'forward', 'right', 'loop3', 'deliver'],
    hints: [
      'Amati petak tempat robot berbelok setelah mengambil buku. Apa yang ada di depannya?',
      'Belokan dilakukan di samping rak. Ada lorong terbuka di atas rak.',
      'Bandingkan posisi robot jika satu langkah dijalankan sebelum belok dan jika dijalankan setelah belok.',
    ],
    reflection: {
      question: 'Untuk memeriksa letak kesalahan, kapan tombol “Satu langkah” paling membantu?',
      choices: ['Saat ingin robot mengabaikan rak.', 'Saat ingin mengamati posisi dan arah setelah setiap perintah.', 'Saat ingin semua kartu otomatis menjadi benar.'],
      correctIndex: 1,
      explanations: [
        'Rak tetap menghalangi robot. Satu langkah membantu mengamati, bukan mengubah aturan peta.',
        'Benar! Dengan mengamati satu perintah setiap kali, kamu bisa mencari titik saat rute mulai salah.',
        'Satu langkah menjalankan kartu yang kamu susun. Kamu tetap yang menyelidiki dan memperbaikinya.',
      ],
    },
  },
  {
    id: 12,
    stageId: 3,
    title: 'Tur perpustakaan',
    concept: 'Rute + urutan + pengulangan',
    difficulty: 'Gabungkan temuanmu',
    story: 'Antar buku melalui tiga bagian lorong. Hitung jarak dan periksa rak pada setiap belokan.',
    objective: 'Gabungkan pengulangan dan belokan untuk melewati rute tanpa menabrak rak.',
    takeaway: 'Jumlah langkah dan tempat belok sama-sama menentukan hasil program.',
    size: { width: 6, height: 5 },
    start: { x: 0, y: 4, dir: 0 },
    book: { x: 3, y: 4 },
    target: { x: 5, y: 0 },
    walls: [{ x: 4, y: 4 }, { x: 4, y: 3 }, { x: 3, y: 1 }, { x: 4, y: 1 }],
    solution: ['loop3', 'pickup', 'left', 'loop2', 'right', 'loop2', 'left', 'loop2', 'deliver'],
    initial: ['loop3', 'pickup', 'left', 'loop3', 'right', 'loop2', 'left', 'loop2', 'deliver'],
    hints: [
      'Amati pengulangan setelah buku diambil. Di petak mana robot mulai menabrak rak?',
      'Robot perlu berbelok di lorong terbuka sebelum mencapai rak di atasnya.',
      'Hitung jarak dari buku sampai titik belok pertama. Cocokkan jarak itu dengan angka pengulangan.',
    ],
    reflection: {
      question: 'Apakah “maju dua kali, belok, maju dua kali” selalu sama dengan “maju empat kali, lalu belok”?',
      choices: ['Ya, karena jumlah majunya sama.', 'Ya, karena belok tidak pernah berpengaruh.', 'Tidak, karena tempat dan waktu beloknya berbeda.'],
      correctIndex: 2,
      explanations: [
        'Jumlah langkahnya sama, tetapi arah sebagian langkah berbeda. Hasil rutenya bisa berbeda.',
        'Belok mengubah arah maju berikutnya. Urutannya berpengaruh pada perjalanan robot.',
        'Benar! Menghitung langkah saja belum cukup. Periksa juga urutan dan titik beloknya.',
      ],
    },
  },
];

export const STAGES = [
  {
    id: 1,
    title: 'Jejak pertama',
    description: 'Kenali urutan kartu, arah robot, dan pola langkah yang berulang.',
    badge: { title: 'Pembaca jejak', description: 'Kamu menyelesaikan empat misi pertama tentang urutan, arah, dan pengulangan.' },
    missionIds: [1, 2, 3, 4],
  },
  {
    id: 2,
    title: 'Pola perjalanan',
    description: 'Gabungkan pola langkah dan belokan. Temukan jalan aman saat rak menghalangi.',
    badge: { title: 'Perangkai pola', description: 'Kamu menyelesaikan empat misi yang menggabungkan urutan, pola, dan jalan aman.' },
    missionIds: [5, 6, 7, 8],
  },
  {
    id: 3,
    title: 'Penyelidik rute',
    description: 'Amati titik belok, hitung setiap bagian lorong, lalu uji hasil perbaikanmu.',
    badge: { title: 'Detektif perpustakaan', description: 'Kamu menyelesaikan empat tantangan rute dengan pengulangan dan rak penghalang.' },
    missionIds: [9, 10, 11, 12],
  },
];

export const MISSIONS = [
  ...ORIGINAL_MISSIONS.map(mission => ({
    ...mission,
    stageId: Math.ceil(mission.id / 4),
    walls: [],
    ...ORIGINAL_LEARNING[mission.id],
  })),
  ...NEW_MISSIONS,
];

export function mapSize(mission) {
  return { width: mission.size?.width ?? 5, height: mission.size?.height ?? 4 };
}
